import os

# Reproducibility
RANDOM_SEED = 42

# Simulation parameters
SITES = ["Site_A", "Site_B", "Site_C"]
COMPOUNDS = ["PFOA", "PFOS"]
SIMULATION_DAYS = 90
SAMPLING_INTERVAL_HOURS = 1
ALERT_COOLDOWN = 12

# Environmental Analysis Constants
STL_PERIOD_ANNUAL = 365
STL_PERIOD_MONTHLY = 30
TREND_STABLE_THRESHOLD = 0.05   # ppt/month, below this = STABLE
CORRELATION_SIG_THRESHOLD = 0.05
COMPLIANCE_WINDOW_DAYS = 30
NOISE_STD = 0.8
BASELINE_MIN = 5.0
BASELINE_MAX = 15.0
SPIKE_CONCENTRATION = (150, 400)
SPIKE_DURATION_HOURS = (6, 12)

# Biosensor calibration
CALIBRATION_A = 0.5
CALIBRATION_B = 2.0

# ML parameters
WINDOW_SIZE = 24
TRAIN_SPLIT = 0.80
FORECAST_HOURS = [24, 48, 72]
RF_ESTIMATORS = 200
RF_MAX_DEPTH = 10
LSTM_UNITS = 64
LSTM_EPOCHS = 10
LSTM_BATCH_SIZE = 32
LSTM_VAL_SPLIT = 0.1

# Anomaly detection
ANOMALY_CONTAMINATION = 0.05
IQR_MULTIPLIER = 1.5

# Alert thresholds (EPA)
EPA_LIMIT_PPT = 70.0
EPA_ADVISORY_PPT = 4.0

# Alert engine
TREND_WINDOW = 6
TREND_THRESHOLD = 0.1

# Visualization
FIGURE_DPI = 300
PLOT_HISTORICAL_DAYS = 7

# Run versioning
RUNS_DIR = "runs"

# API
API_HOST = "0.0.0.0"
API_PORT = 8000

# Report
REPORT_FILENAME = "pfas_report.txt"
HTML_REPORT_FILENAME = "pfas_report.html"
